services:
  - type: web
    name: pdf-query-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: GROQ_API_KEY
        value: YOUR_API_KEY_HERE
